r"""
GEOMETRIC diagnostics — how far can the patch reach, independent of semantics.

Everything here is TARGET-INDEPENDENT, LOSS-INDEPENDENT and LABEL-FREE by
construction. That is what makes it a control rather than a correlate: it
measures the model's effective receptive field with semantics held out, so it
can be compared across architectures, datasets and objectives without
confounds. It is also why measure_erf.py can run on ADE20K weights.
"""
from __future__ import annotations

from contextlib import contextmanager
from typing import List, Tuple

import numpy as np
import torch

from ..data.cityscapes import upsample_to
from ..losses.reach import centroid, distance_map

RINGS = [(0, 150), (150, 300), (300, 450), (450, 650), (650, 900), (900, 1200)]


@torch.no_grad()
def _probe(model, imgs, patch, clean, n_probes, H, W):
    """n_probes random parameters -> mean per-pixel argmax-change rate."""
    accum = torch.zeros(H, W, device=imgs.device)
    footprint = None
    for _ in range(n_probes):
        patch.param.data = torch.randn_like(patch.param) * 3.0
        # PROJECT, do not assume. The old probe set the parameter and went
        # straight to apply(), which is only correct for a parameterisation
        # whose render is bounded on its own. Under csf_param='pgd' the
        # parameter IS the residual, so an unprojected randn*3 is a residual of
        # ~3 in pixel units -- around 1000x tau -- and the "tau-matched" null
        # would have been a near-maximal stimulus instead. project() applies
        # whatever bound the mode actually has, so this stays correct for every
        # mode without knowing which one it is.
        patch.project()
        patched, fp = patch.apply(imgs)
        footprint = fp if footprint is None else footprint
        accum += (upsample_to(model(patched), (H, W)).argmax(1)
                  != clean).float().mean(0)
    return accum / n_probes, footprint


@contextmanager
def _unconstrained(patch):
    """
    Render the patch as RAW PIXELS for the duration of the block.

    mode='raw' renders sigmoid(param), so a random parameter becomes a
    full-contrast random square, and apply() composites it through the exact
    same path every other pixel mode uses -- no mirrored compositing logic to
    drift out of agreement with Patch.apply().

    Only the render is switched. The parameter, the placement, the shape mask
    and the footprint are untouched, so the stimulus differs from the null in
    CONTRAST ALONE and the two curves stay comparable.
    """
    saved = patch.cfg.mode
    patch.cfg.mode = "raw"
    try:
        yield
    finally:
        patch.cfg.mode = saved


@torch.no_grad()
def receptive_field(model, imgs, patch, n_probes: int = 16,
                    rings: List[Tuple[int, int]] = None, log=print):
    """
    Empirical ERF: fill the patch region with random noise and record which
    pixels change their argmax. TWO stimuli, because one of them was wrong.

        ceiling : an UNCONSTRAINED max-contrast random square. This is the
                  architectural limit -- what any patch of this size at this
                  position could propagate, whatever its loss or budget.
        null    : a random patch under the patch's OWN parameterisation, i.e.
                  at the SAME tau as the attack. An unoptimised perturbation of
                  equal perceptual cost. The gap between this and the trained
                  reach curve is what optimisation bought.

    THE BUG THIS FIXES. There was one stimulus, it was generated by writing a
    random parameter and calling apply(), and it was documented as "MAXIMAL
    STIMULUS -- an optimised patch cannot exceed what the architecture will
    propagate, so this is an upper bound on reach". For mode='csf' that is
    false: the csf reparameterisation renormalises ANY parameter to tau, so the
    probe was an INVISIBLE random residual, not a maximal one. It measured
    0.44-1.96% change in the near field on four architectures and printed
    "falls below 5% at ~0px" for all of them, while the trained patch on the
    same image and model changed 98.9% of pixels at 71px -- an "upper bound"
    exceeded fifty-fold by the thing it was supposed to bound. The number was
    not wrong; the label was. It was a null baseline all along, and the ceiling
    it claimed to be had never been measured.

    For pixel modes (raw, lap, ...) a random parameter ALREADY renders a
    full-contrast square, so the two stimuli coincide and only one curve is
    reported. The split is only meaningful where a perceptual budget sits
    between the parameter and the pixels.

    Returns (ceiling_reach [H,W], ring_stats [(lo, hi, ceiling_pct, null_pct)]).
    """
    rings = rings or RINGS
    B, _, H, W = imgs.shape
    clean = upsample_to(model(imgs), (H, W)).argmax(1)

    original = patch.param.detach().clone()
    bounded = patch.cfg.mode in ("csf", "universal_csf")
    # gan carries a LATENT, not a pixel grid, so the raw render would be handed
    # a tensor of the wrong shape. Its native probe is a random BigGAN sample,
    # which is the only stimulus that mode can produce anyway.
    can_unconstrain = (tuple(patch.param.shape)
                       == (3, patch.cfg.size, patch.cfg.size))

    null_reach, footprint = _probe(model, imgs, patch, clean, n_probes, H, W)
    if bounded and can_unconstrain:
        with _unconstrained(patch):
            ceiling_reach, _ = _probe(model, imgs, patch, clean,
                                      n_probes, H, W)
    else:
        ceiling_reach = null_reach
    patch.param.data = original

    dist = distance_map(H, W, *centroid(footprint), imgs.device)
    outside = ~footprint[0]

    split = bounded and can_unconstrain
    stats = []
    log(f"\n[geometric] empirical receptive field "
        f"(random-patch probe, n={n_probes}):")
    if split:
        log("            ceiling — unconstrained max-contrast square: the "
            "architectural limit,")
        log("                      NOT a patch this attack could build")
        log(f"            null    — random patch at the SAME tau "
            f"({patch.cfg.csf_threshold:g}) as the attack:")
        log("                      what an unoptimised perturbation of equal "
            "perceptual cost reaches")
        log(f"    {'ring(px)':>14}  {'ceiling':>9}  {'null':>9}")
    else:
        log("            unconstrained random square — target-independent, "
            "an upper bound on reach")

    for lo, hi in rings:
        ring = outside & (dist >= lo) & (dist < hi)
        if ring.sum() == 0:
            continue
        c = ceiling_reach[ring].mean().item() * 100
        n = null_reach[ring].mean().item() * 100
        stats.append((lo, hi, c, n))
        if split:
            log(f"    {f'{lo}-{hi}':>14}  {c:8.2f}%  {n:8.2f}%")
        else:
            log(f"    {lo:5d}-{hi:<5d}px : {c:6.2f}%  {'#' * int(c)}")

    # THE THRESHOLD LINE, said honestly. The old version printed
    # "falls below 5% at ~0px" whenever the FIRST ring was already under 5% --
    # a degenerate case it reported as if it were a measured crossing distance,
    # and the case that fired on all four architectures.
    below = [lo for lo, _, c, _ in stats if c < 5.0]
    if below and stats and below[0] == stats[0][0]:
        log(f"    -> ceiling is already below 5% in the FIRST ring: this model "
            f"propagates almost")
        log(f"       nothing from a patch this size. A trained reach curve "
            f"far above this is a")
        log(f"       measurement problem, not a result — check that the probe "
            f"and the attack")
        log(f"       composite the same way.")
    elif below:
        log(f"    -> ceiling falls below 5% beyond {below[0]}px")
    else:
        log(f"    -> ceiling stays above 5% out to {stats[-1][1]}px"
            if stats else "    -> no rings measured")
    return ceiling_reach, stats


@torch.no_grad()
def scale_sweep(model, imgs, patch, scales=(0.15, 0.25, 0.35, 0.50),
                n_probes: int = 8, log=print):
    """
    Does reach GROW with patch size, and how fast?

    The two-factor model predicts d_max ~ sigma * sqrt(2 ln(kappa*sqrt(3)*p / m)),
    i.e. reach grows only as sqrt(log p). If the measurement matches that weak
    scaling, "just use a bigger patch" is quantitatively ruled out: covering
    another 200px would need a patch larger than the image.

    Restores the original scale before returning.
    """
    B, _, H, W = imgs.shape
    clean = upsample_to(model(imgs), (H, W)).argmax(1)
    original_scale, original_param = patch.cfg.scale, patch.param.detach().clone()

    out = {}
    log("\n[geometric] patch-scale sweep (reach vs patch size):")
    for s in scales:
        patch.cfg.scale = s
        accum = torch.zeros(H, W, device=imgs.device)
        fp = None
        for _ in range(n_probes):
            patch.param.data = torch.randn_like(patch.param) * 3.0
            patched, f = patch.apply(imgs)
            fp = f if fp is None else fp
            accum += (upsample_to(model(patched), (H, W)).argmax(1)
                      != clean).float().mean(0)
        reach = accum / n_probes
        dist = distance_map(H, W, *centroid(fp), imgs.device)
        outside = ~fp[0]

        row = []
        for lo, hi in RINGS[:5]:
            ring = outside & (dist >= lo) & (dist < hi)
            if ring.sum():
                row.append(((lo + hi) // 2, reach[ring].mean().item() * 100))
        out[s] = row
        log(f"    scale {s:.2f} (p={int(H*s)}px): "
            + "  ".join(f"{d}px={r:.1f}%" for d, r in row))

    patch.cfg.scale, patch.param.data = original_scale, original_param
    return out


def plot_erf(stats, out_path, title="Empirical receptive field"):
    """
    stats rows are (lo, hi, ceiling_pct, null_pct). The null series is drawn
    only when it differs from the ceiling — for pixel modes the two stimuli are
    the same thing and a second identical line would imply a comparison that
    was never made.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    d = [(lo + hi) / 2 for lo, hi, _, _ in stats]
    ceiling = [c for _, _, c, _ in stats]
    null = [n for _, _, _, n in stats]
    split = any(abs(c - n) > 1e-9 for c, n in zip(ceiling, null))

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(d, ceiling, "-o", color="#c44e52",
            label="ceiling (unconstrained square)" if split else None)
    if split:
        ax.plot(d, null, "-s", color="#4c72b0",
                label="null (random patch at the same tau)")
    ax.axhline(5, color="gray", ls="--", lw=0.8, label="5% threshold")
    ax.set_xlabel("distance from patch centre (px)")
    ax.set_ylabel("prediction-change rate (%)")
    ax.set_title(f"{title}\n"
                 + ("random-patch probe — architectural ceiling vs "
                    "tau-matched null" if split else
                    "unconstrained random square — target-independent ceiling"))
    ax.legend()
    ax.set_ylim(bottom=0)
    plt.tight_layout()
    fig.savefig(out_path, dpi=130, bbox_inches="tight")
    plt.close(fig)
